### ISSUE TITLE
Buildpack failing

### ISSUE THREAD

**Issue by JMurphyWeb** [Shopify/heroku-buildpack-mysql#7]
For the last few months I have had a failing build due to an issue with this buildpack. 

In debugging, I am running my app with only this buildpack on Heroku Cedar-14 stack.

<img width="861" alt="screen shot 2017-07-25 at 15 02 21" src="https://user-images.githubusercontent.com/12638261/28575960-5d6b6b0e-714a-11e7-8e0d-3b9533c2d0d9.png">

I getting the following error when attempting deployment.

Would really appreciate some help.

```
-----> MySQL Client app detected
/app/tmp/buildpacks/15b0580d616a9b66dad1c5d4bd63e276920b0d472e5ab68138844907834bb4af83d7d7589c5aeefa63078570f6f346c110731dde32d7bbc18747d0cc38bbf58f/lib/build_pack.rb:1:in `require_relative': /app/tmp/buildpacks/15b0580d616a9b66dad1c5d4bd63e276920b0d472e5ab68138844907834bb4af83d7d7589c5aeefa63078570f6f346c110731dde32d7bbc18747d0cc38bbf58f/lib/build_pack/installer.rb:50: syntax error, unexpected tLABEL, expecting ')' (SyntaxError)
      def run_command_with_message(command:, message:)
                                           ^
/app/tmp/buildpacks/15b0580d616a9b66dad1c5d4bd63e276920b0d472e5ab68138844907834bb4af83d7d7589c5aeefa63078570f6f346c110731dde32d7bbc18747d0cc38bbf58f/lib/build_pack/installer.rb:74: syntax error, unexpected keyword_end, expecting $end
	from /app/tmp/buildpacks/15b0580d616a9b66dad1c5d4bd63e276920b0d472e5ab68138844907834bb4af83d7d7589c5aeefa63078570f6f346c110731dde32d7bbc18747d0cc38bbf58f/lib/build_pack.rb:1:in `<top (required)>'
	from /app/tmp/buildpacks/15b0580d616a9b66dad1c5d4bd63e276920b0d472e5ab68138844907834bb4af83d7d7589c5aeefa63078570f6f346c110731dde32d7bbc18747d0cc38bbf58f/bin/compile:6:in `require_relative'
	from /app/tmp/buildpacks/15b0580d616a9b66dad1c5d4bd63e276920b0d472e5ab68138844907834bb4af83d7d7589c5aeefa63078570f6f346c110731dde32d7bbc18747d0cc38bbf58f/bin/compile:6:in `<main>'
 !     Push rejected, failed to compile MySQL Client app.
 !     Push failed
```

**Comment by JMurphyWeb** [comment]
I enhanced the Readme but don't have push rights.

Please add the following to the readme:

```
## Instructions

If using with a `node.js` application, ensure that:
- You have this buildpack registered before the `heroku/nodejs` one
- You are using heroku's `heroku-16` stack as opposed to the `cedar-14` stack
```

**Comment by sebbean** [comment]
same issue here

i thin even if not using node.js (i'm using php)
